### ISSUE TITLE
Non admin account can add a faculty account

### ISSUE THREAD

**Issue by ZacharyB19** [git-keeper/git-keeper#117]
This issue was brought up with Dr. Coleman. An account that isn't an admin can still create faculty account seven thought that should not be allowed.

**Comment by sommern** [comment]
This was fixed with pull request #118, which still needs merging

**Comment by bjcoleman** [comment]
Zach-

Merge the code from this PR with your current tests, and if the test
passes, you can add a comment to the PR stating that is the case.

Professor Coleman
