### ISSUE TITLE
Distinction between Add Faculty and Setup Faculty Accounts

### ISSUE THREAD

**Issue by ZacharyB19** [git-keeper/git-keeper#120]
This is a minor refractoring issue but it appears that the names of these two commands are a little confusing.

As of now, Add Faculty adds a specified faculty name onto the server but does not setup SSH keys. It simply checks that the account is created. 

Setup Faculty Accounts can take any username and setup SSH keys and config file for them. 

My suggested improvement would be to rename Add Faculty to Add Faculty To Server to better tell what it is doing OR get rid of one of these and have one general add faculty command.

**Comment by sommern** [comment]
I agree this is confusing. Another option would be to keep the naming consistent by having `Add Faculty To Server` and `Add Faculty To Client`, and then have `Add Faculty` do both of these.
