### ISSUE TITLE
Validate characters in class CSV files

### ISSUE THREAD

**Issue by sommern** [git-keeper/git-keeper#157]
Faculty may accidentally upload CSV files containing non-printable characters, or other characters that could cause problems as usernames, and file and directory names. This should be caught when a class is added or modified.

**Comment by coderforlife** [comment]
One thing to note is that the issue that identified this had a BOM (byte order mark) at the start of the file which is a completely legitimate set of non-printable characters which indicates that the file has a specific encoding (such as UTF-8). It is supposed to be handled by all Unicode-aware readers.

**Comment by sommern** [comment]
This was addressed with #169
